config/routes.rb
Rails.application.routes.draw do
  root to: "pokemons#index"
  resources :pokemons, only: [:show] do
    collection do
      get :search
      get :random
    end
    resources :pokeballs, only: [:create]
  end

  resources :trainers, only: [:index, :show, :new, :create]
  resources :pokeballs, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokeball.rb
class Pokeball < ApplicationRecord
  belongs_to :trainer
  belongs_to :pokemon

  validates :caught_on, presence: true
  validates :location, presence: true

  validates :pokemon_id, uniqueness: { scope: :trainer_id, message: "has already been caught by this trainer" }
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokeballs, dependent: :destroy
  has_many :trainers, through: :pokeballs

  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :element_type, presence: true
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :pokeballs, dependent: :destroy
  has_many :pokemons, through: :pokeballs

  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :age, presence: true
  validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pokeballs_controller.rb
class PokeballsController < ApplicationController

  def create
    @pokemon = Pokemon.find(params[:pokemon_id])


    if succesfull_catch?
      @pokeball = Pokeball.new(pokeballs_params)
      @pokeball.pokemon = @pokemon
      @pokeball.trainer = Trainer.find(params[:pokeball][:trainer_id])
      if @pokeball.save
        redirect_to trainer_path(@pokeball.trainer), notice: 'Pokemon caught!'
      else
        render pokemon, status: :unprocessable_entity
      end
    else
      redirect_to root_path(@pokemons), status: :see_other
    end
  end

  def destroy
    @pokeball = Pokeball.find(params[:id])
    @pokeball.destroy
    redirect_to trainer_path(@pokeball.trainer), notice: 'Pokéball released.'
  end

  private

  def pokeballs_params
    params.require(:pokeball).permit(:caught_on, :location, :trainer_id)
  end

  def succesfull_catch?
    rand < 0.5
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @pokeball = Pokeball.new
  end

  def search
    if params[:query].present?
      @pokemons = Pokemon.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @pokemons = Pokemon.all
    end
    render :index
  end

  def random
    @pokemon = Pokemon.all.sample
    if @pokemon
      redirect_to pokemon_path(@pokemon)
    else
      redirect_to root_path, alert: "No Pokémon available."
    end
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show]

  def index
    @trainers = Trainer.all
  end

  def show
  end

  def new
    @trainer = Trainer.new
  end

  def create
    @trainer = Trainer.new(trainer_params)
    if @trainer.save
      redirect_to trainers_path, status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_trainer
    @trainer = Trainer.find(params[:id])
  end

  def trainer_params
    params.require(:trainer).permit(:name, :age, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPokemon</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Jersey+10&family=Pixelify+Sans:wght@400..700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pokemons/index.html.erb
<div class="container mt-3">

  <h1><%= link_to "Pokedex", root_path  %></h1>

  <h6><%= link_to "< Trainers", trainers_path %></h6>

  <h6><%= link_to "Random Pokémon", random_pokemons_path %></h6>

<div class="w-100 mb-3">
  <%= simple_form_for :search, url: search_pokemons_path, method: :get, html: { class: "w-100" } do |f| %>
    <div>
      <%= f.input :query, label: false, placeholder: "Search a Pokémon...", input_html: { class: "form-control", name: 'query' } %>
      <%= f.submit "Search", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>



  <% if @pokemons.empty? %>
      <p >No Pokémon found.</p>
  <% end %>

  <div class="row mb-3">
    <% @pokemons.each do |pokemon| %>
      <div class="col-md-4 col-sm-6 col-lg-3 mb-3">
        <div class="card card-pokemon">
          <% if pokemon.photo.attached? %>
            <%= link_to pokemon_path(pokemon) do %>
              <div>
                <%= cl_image_tag pokemon.photo.key, class: "card-img-top img-fluid", alt: pokemon.name %>
              </div>
              <div class="card-body text-center">
                <h5><%= pokemon.name %></h5>
                <p><strong>Type :</strong> <%= pokemon.element_type %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>



</div>

app/views/pokemons/show.html.erb
<div class="container pt-3">

  <h3><%= link_to "< Pokedex", root_path  %></h3>

  <div class="row mt-3">
    <div class="col-md-6 mb-3">
      <div class="card card-pokemon">
        <div>
          <%= cl_image_tag @pokemon.photo.key, class: "card-img-top img-fluid", alt: @pokemon.name %>
          <div class="card-body text-center">
            <h5><%= @pokemon.name %></h5>
            <p><strong>Type :</strong> <%= @pokemon.element_type %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6 mb-3">
      <%= simple_form_for [@pokemon, @pokeball] do |f| %>
        <%= f.association :trainer, label: "Who is trying their luck?" %>
        <%= f.input :location, label: "Where are you?"%>
        <%= f.input :caught_on, label: "Date of Capture", as: :date %>
        <%= f.submit "Catch Pokémon", class: "btn btn-primary" %>
      <% end %>
    </div>


  </div>
</div>

app/views/trainers/index.html.erb
<div class="container">

  <h3><%= link_to "< Pokedex", root_path  %></h3>

  <h1 class="mb-4">Let's get training !</h1>

  <div class="row mb-3 justify-content-center">
    <% @trainers.each do |trainer| %>
      <div class="col-md-4 col-lg-3 mb-3">
        <div class="card card-trainer">
          <% if trainer.photo.attached? %>
            <%= link_to trainer_path(trainer) do %>
              <div>
                <%= cl_image_tag trainer.photo.key, class: "card-img-top img-fluid", alt: trainer.name %>
              </div>
              <div class="card-body text-center">
                <h5><%= trainer.name %></h5>
                <p><strong><%= trainer.age %></strong> years old </p>
                <p>Trains <strong><%= trainer.pokemons.count %></strong> pokémon<%= trainer.pokemons.count  > 1 ? "s" : "" %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <%= link_to "New trainer", new_trainer_path, class:"btn btn-primary" %>
</div>

app/views/trainers/new.html.erb
<div class="container">
<h3><%= link_to "< Pokedex", root_path  %></h3>
<%= link_to "< All Trainers", trainers_path %>

<h1>Sign up to train</h1>

<%= simple_form_for (@trainer) do |f| %>
  <%= f.input :name %>
  <%= f.input :age %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class:"btn btn-primary"%>
<% end %>


</div>

app/views/trainers/show.html.erb
<div class="container">
  <h3><%= link_to "< Pokedex", root_path  %></h3>
  <%= link_to "< Trainers", trainers_path %>

  <div class="row mb-3">

  <h1><%= @trainer.name %> is going to catch 'em all!</h1>
    <%# Trainer Card %>
    <div class="col-md-4">
      <div class="card card-trainer fixed">
        <% if @trainer.photo.attached? %>
          <div>
            <%= cl_image_tag @trainer.photo.key, class: "card-img-top img-fluid", alt: @trainer.name %>
          </div>
          <div class="card-body text-center">
            <h5><%= @trainer.name %></h5>
            <p><strong>Age :</strong> <%= @trainer.age %></p>
          </div>
        <% end %>
      </div>
    </div>

    <%# Pokemon Cards %>
    <div class="col-md-8">
    <h2>Their Pokémon</h2>
      <div class="row">
        <% @trainer.pokeballs.each do |pokeball| %>
          <div class="col-md-6  col-lg-4 mb-3">
            <div class="card card-pokemon d-flex flex-column h-100">
              <% if pokeball.pokemon.photo.attached? %>
                <div>
                  <%= cl_image_tag pokeball.pokemon.photo.key, class: "card-img-top img-fluid", alt: pokeball.pokemon.name %>
                  <div class="card-body text-center flex-grow-1">
                    <h5><%= pokeball.pokemon.name %></h5>
                    <p><strong>Type :</strong> <%= pokeball.pokemon.element_type %></p>
                    <p><strong>Caught on : </strong><%= pokeball.caught_on.strftime("%B %d, %Y") %></p>
                    <p><strong>At : </strong><%= pokeball.location %></p>
                  </div>
                  <div class="d-flex justify-content-center mt-auto">
                    <%= button_to "Release", pokeball_path(pokeball), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger ms-2 my-1" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>